### ISSUE TITLE
Typo in Word Analogies post, re. Co-occurrence Shifted PMI Theorem?

### ISSUE THREAD

**Issue by drscotthawley** [kawine/kawine.github.io#1]
Dear Kawine,

I'm enjoying your blog post https://kawine.github.io/blog/nlp/2019/06/21/word-analogies.html
Thank you for sharing.

For the last of 3 bullet points for the Co-occurrence Shifted PMI Theorem, it looks like you have the same thing repeated 3 times:

> {Ma,⋅−My,⋅, Ma,⋅−My,⋅, Ma,⋅−My,⋅} are linearly dependent for any two word pairs

Should those Ma,.-My,.'s be different? e.g. Equation (3) in [the paper](https://arxiv.org/pdf/1810.04882.pdf) has something similar but worded differently (in terms of rank) where they are different.

Thanks again for sharing. I'm not an NLP specialist, just trying to learn!

**Comment by kawine** [comment]
That was a typo, sorry -- the three expressions should correspond to what's in the paper. 

Thanks so much for catching the typo! Just pushed an edit.

**Comment by drscotthawley** [comment]
My pleasure. Thank you for your post and your helpful paper. I'd been wondering how these embedding spaces manage to have any algebraic or metric structure at all.  Now I get it; you & your collaborators did a great job showing why!
